print("-RULES OF YAHTZEE:"
      "\n-Everyone get 13 turns"
      "\n-5 players no more"
      "\n-You use 5 dices"
      "\n-When your turn you roll 5 dices up to 3 times. Each roll you can decide to keep or re-roll"
      "\n-Scoring depends on what roll you get:"
      "\n-3 of a kind is at least 3 dice the same;score is total of all dice "
      "\n-4 of a kind at least 4 dice is the same; Score is total of all dice"
      "\n-Full House 3 of one number and 2 of another; score total will be 25"
      "\n-Small Straight Four consecutive numbers example (1-2-3-4);score will be 30 points"
      "\n-Large straight 5 consecutive numbers like (2-3-4-5-6);score will be 40 points"
      "\n-Chance score this with any combination;The score is total of dice"
      "\n-Yahtzee if all the dice are the same; The score is 50 points "
      "\n-Yahtzee-bonus If you roll another Yahtzee you score additional 100 points. Only if you have filled yahtzee in score sheet"
      "\n-Then do this for 13 times."
      "\n-add up the score and highest wins")
